### ISSUE TITLE
Skelton - Skeleton 

### ISSUE THREAD

**Issue by rileyrg** [Kyure-A/el-project#2]
Possibly you mean "skeleton".

**Comment by Kyure-A** [comment]
It became clear that I can't speak English... I'll fix it.

**Comment by rileyrg** [comment]
🤣 I just thought better to fix it early on 🤣

**Comment by Kyure-A** [comment]
fixed at cd5d717df7d809887041932fb9cb13387e50bd57! 
Thank you 👍🏻
